version: "3.3"

services:
  cows-frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - "5180:5180"
  cows-backend:
    build:
      context: ../java-backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_MODE=1
    env_file:
      - ../java-backend/.env
    ports:
      - "8030:8030"
